"""Base strategy interface for 0DTE SPX trading."""

from abc import ABC, abstractmethod
from dataclasses import dataclass
from typing import Optional

from src.data.market_data import MarketData


@dataclass
class Signal:
    """Trading signal generated by a strategy."""
    direction: str          # "call" or "put"
    strength: float         # 0.0 to 1.0, higher = stronger signal
    strategy_name: str
    strike_offset: float    # Points from current price for strike selection
    reason: str             # Why this signal was generated

    @property
    def is_bullish(self) -> bool:
        return self.direction == "call"

    @property
    def is_bearish(self) -> bool:
        return self.direction == "put"


class BaseStrategy(ABC):
    """Abstract base class for 0DTE strategies."""

    def __init__(self, name: str):
        self.name = name

    @abstractmethod
    def evaluate(self, data: MarketData) -> Optional[Signal]:
        """
        Evaluate market conditions and return a signal if entry criteria are met.

        Returns None if no trade should be taken.
        """
        pass

    @abstractmethod
    def get_optimal_strike_offset(self, data: MarketData, direction: str) -> float:
        """
        Calculate the optimal strike price offset from current price.

        Positive = OTM calls or ITM puts
        Negative = ITM calls or OTM puts

        For aggressive trading, we want slightly OTM for max leverage.
        """
        pass
